version: '3.8'

services:
  # Aplicação NestJS
  payments-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: payments-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=payments_db
      - TEMPORAL_SERVER_URL=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-7639895969324989-092908-29a76b93a0570b89017f6f04903fe8ab-2720512788
      - MERCADOPAGO_PUBLIC_KEY=APP_USR-fe8040ce-fd1c-46b0-8400-14b046ad80f8
      - MERCADOPAGO_WEBHOOK_URL=https://your-domain.ngrok.io/api/webhooks/mercadopago/notifications
      - PAYMENT_SUCCESS_URL=http://localhost:3001/payment/success
      - PAYMENT_FAILURE_URL=http://localhost:3001/payment/failure
      - PAYMENT_PENDING_URL=http://localhost:3001/payment/pending
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - payments-network
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_healthy
    command: npm run start:dev

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: payments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - payments-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL para Temporal
  temporal-postgres:
    image: postgres:16-alpine
    container_name: temporal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    networks:
      - payments-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.22.0
    container_name: temporal-server
    restart: unless-stopped
    depends_on:
      temporal-postgres:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=5433
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_AUTHORIZATION=false
      - ENABLE_TLS=false
      - TEMPORAL_BROADCAST_ADDRESS=0.0.0.0
      - TEMPORAL_CLI_SHOW_STACKS=1
    ports:
      - "7233:7233"  # gRPC
      - "7234:7234"  # Membership
      - "7235:7235"  # History
      - "7239:7239"  # Worker
    networks:
      - payments-network
    healthcheck:
      test: ["CMD", "temporal", "operator", "cluster", "health"]
      interval: 5s
      timeout: 5s
      retries: 30

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: temporal-ui
    restart: unless-stopped
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000,http://localhost:8080
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8080:8080"
    networks:
      - payments-network

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: payments-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - payments-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  temporal_postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  payments-network:
    driver: bridge
